id: I1B1946B0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:56:26+00:00'
last_modified: '2022-06-07T17:19:16.335754+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W13994
  title: བླ་མ་ཞང་བརྩོན་འགྲུས་གྲགས་པའི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    34B4:
      image_group_id: I3025
      title: ''
      total_pages: 508
      order: 1
      base_file: 34B4.txt
    D2B8:
      image_group_id: I3026
      title: ''
      total_pages: 550
      order: 2
      base_file: D2B8.txt
    '8500':
      image_group_id: I3027
      title: ''
      total_pages: 719
      order: 3
      base_file: 8500.txt
    9EE2:
      image_group_id: I3028
      title: ''
      total_pages: 585
      order: 4
      base_file: 9EE2.txt
    4C97:
      image_group_id: I3029
      title: ''
      total_pages: 673
      order: 5
      base_file: 4C97.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
