id: I1B1946B0
legacy_id: P003065
ocr_import_info:
  bdrc_scan_id: W13994
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:51:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T12:23:12.497334+00:00'
last_modified: 2022-08-30 20:27:03.859340
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W13994
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW13994
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མ་ཞང་བརྩོན་འགྲུས་གྲགས་པའི་གསུང་འབུམ།
  author: བླ་མ་ཞང་བརྩོན་འགྲུས་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.488364790773891
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I3028:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3028
      total_pages: 585
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3028.txt
    statistics:
      ocr_word_median_confidence_index: 0.4699999988079071
      ocr_word_mean_confidence_index: 0.4960760167472189
    legacy_id: v004
  I3025:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3025
      total_pages: 508
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3025.txt
    statistics:
      ocr_word_median_confidence_index: 0.46000000834465027
      ocr_word_mean_confidence_index: 0.4911583503603437
    legacy_id: v001
  I3026:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3026
      total_pages: 550
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3026.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5112681903223036
    legacy_id: v002
  I3029:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3029
      total_pages: 673
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3029.txt
    statistics:
      ocr_word_median_confidence_index: 0.3799999952316284
      ocr_word_mean_confidence_index: 0.45239988943742593
    legacy_id: v005
  I3027:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3027
      total_pages: 719
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3027.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5131895860739405
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
